### PR TITLE
Added option for setting clock id

### PR DESCRIPTION
**Pull request by alexandreyc**
Hi,

I needed to print the real time timestamp instead of the monotic one (`CLOCK_MONOTIC` vs `CLOCK_REALTIME`), so I added a switch option (`-T`) to do it. Can you give me feedback about my modest contribution ?

Thanks,

### CODE REVIEW

**Comment by br101** [comment]
Hmmm... We definetly need to use monotonic time in the timeout function, otherwise the timeout can be messed up by system clock changes (e.g. NTP running in background). This is also true for other regular "timing" issues, like channel changes. We need to use monotonic time there.
Where exactly do you need the "real time"? It may be better to simply add the "real time" for that.

**Comment by alexandreyc** [comment]
Indeed I didn't consider possible internal issues with the real time clock... I need "real time" just in the output messages. Should I update my option to only affect output timing instead of the whole timing thing ?

**Comment by br101** [comment]
Well, I think it makes sense to have all output time in "real time" so there is no need to select it as a command line option. I suggest to rename `the_time` to `time_mono` and introduce a new `time_real` and use it where appropriate.

**Comment by alexandreyc** [comment]
Fine. I'll do it quickly. Thanks for your feedback

**Comment by alexandreyc** [comment]
Done. Can you confirm that `update_clock` must use `time_real` ?

**Comment by br101** [comment]
Thanks!

**Pull request merged**
